### ISSUE TITLE
install.lua wrong url

### ISSUE THREAD

**Issue by Commandcracker** [unicornpkg/unicornpkg.github.io#4]
## Error Message
![Screenshot_20221121_220629](https://user-images.githubusercontent.com/49335821/203158202-bcd5d0e5-fb2c-45a5-aec5-641f76604b38.png)

## Location of the "bug"
https://github.com/unicornpkg/unicornpkg.madefor.cc/blob/ab488c3750a3b0cbc8c4d370cc7a4b8d07c96520/how-tos/installation.md?plain=1#L11

## Additional "Context"
Working Url: https://raw.githubusercontent.com/unicornpkg/wing/main/install.lua

**Comment by tomodachi94** [comment]
Thank you for the report!
